provider: github
action_refresh_delay: 60
columns:
  - name: New
    cleanup: "~/.config/lazyboards/scripts/cleanup.sh {session}"
    actions:
      R:
        name: Refine
        type: shell
        command: "~/.config/lazyboards/scripts/refine.sh {number} {session}"
  - name: Refined
    cleanup: "~/.config/lazyboards/scripts/cleanup.sh {session}"
    actions:
      I:
        name: Implement
        type: shell
        command: "~/.config/lazyboards/scripts/implement.sh {number} {session} {tags}"
      D:
        name: Design
        type: shell
        command: "~/.config/lazyboards/scripts/design.sh {number} {session}"
  - name: Designed
  - name: Implemented
actions:
  C:
    name: Claude Code
    type: shell
    command: "~/.config/lazyboards/scripts/claude.sh"
  S:
    name: Git Sync
    type: shell
    command: "~/.config/lazyboards/scripts/sync.sh"
  P:
    name: Git Pull
    type: shell
    command: "git pull"
